#r "nuget: Microsoft.Extensions.Configuration, 9.0.0"
#r "nuget: Microsoft.Extensions.Configuration.FileExtensions, 9.0.0"
#r "nuget: Microsoft.Extensions.Configuration.Json, 9.0.0"
#r "nuget: Microsoft.Extensions.Configuration.EnvironmentVariables, 9.0.0"
#r "nuget: Microsoft.Extensions.Logging.Abstractions, 9.0.0"
#r "nuget: Microsoft.Extensions.Caching.Memory, 9.0.0"
// #r "nuget: FSharp.Data, 6.4.0"  // Type provider warning - comment out if not used
#r "nuget: FSharp.Control.AsyncSeq, 3.2.1"
#r "nuget: FSharp.SystemTextJson, 1.3.13"
#r "nuget: DotNetEnv, 3.1.1"
#r "nuget: Microsoft.Azure.Cosmos, 3.45.2"
#r "nuget: Azure.Search.Documents, 11.6.0"
#r "nuget: Microsoft.Azure.Core.Spatial, 1.1.0"
#r "nuget: System.IO.Pipelines, 8.0.0"
#r "nuget: StackExchange.Redis, 2.8.16"
#r "nuget: Microsoft.AspNetCore.Http.Abstractions, 2.2.0"
#r "nuget: Spectre.Console, 0.47.0"
